<?php

return $products = [
  //prodotti ristorante id=1 (da id 1 a id 13)
  [
    "restaurant_id" => 1,
    "name" => "Marinara",
    "image" => "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/vimdb/83535_751-0-4864-4864.jpg",
    "slug" => "marinara",
    "description" => "pomodoro, aglio e origano",
    "price" => 3.80,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Margherita",
    "slug" => "margherita",
    "image" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
    "description" => "pizza pomodoro e mozzarella",
    "price" => 4.50,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Margherita con funghi",
    "slug" => "margherita-con-funghi",
    "image" => "https://i0.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2019/10/4102_Pizza.jpg?resize=895%2C616&ssl=1",
    "description" => "pomodoro, mozzarella e funghi champignon",
    "price" => 5.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Crostino",
    "slug" => "crostino",
    "image" => "https://www.lacucinaimperfetta.com/wp-content/uploads/2014/09/Focaccia-prosciutto-e-formaggio.jpg",
    "description" => "mozzarella e prosciutto cotto",
    "price" => 5.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Napoli",
    "slug" => "napoli",
    "image" => "https://wips.plug.it/cips/buonissimo.org/cms/2012/07/pizza-napoli-5.jpg",
    "description" => "pomodoro, mozzarella e filetti di alici",
    "price" => 5.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Diavola",
    "slug" => "diavola",
    "image" => "https://www.cucinare.it/uploads/wp-content/uploads/2015/10/ricetta_pizza_alla_diavola.jpg",
    "description" => "pomodoro, mozzarella e ventricina",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Bianca Boscaiola",
    "slug" => "bianca-boscaiola",
    "image" => "https://i.ytimg.com/vi/SwPvqV_qCCA/maxresdefault.jpg",
    "description" => "mozzarella, funghi champignon e salsiccia di Norcia",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Bianca ai 4 Formaggi",
    "slug" => "bianca-ai-4-formaggi",
    "image" => "https://wips.plug.it/cips/buonissimo.org/cms/2012/12/10798952_l.jpg",
    "description" => "mozzarella, gorgonzola DOP, provola affumicata e grana DOP",
    "price" => 6.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Bianca Ortolana",
    "slug" => "bianca-ortolana",
    "image" => "https://www.granarolo.it/system/granarolo_consumer/attachments/data/000/001/792/original/pizza-ortolana.jpg?1490627997",
    "description" => "mozzarella, funghi champignon, zucchine e melanzane grigliate",
    "price" => 6.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Capricciosa",
    "slug" => "capricciosa",
    "image" => "https://i2.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2017/12/3240_Pizza.jpg?resize=895%2C616&ssl=1",
    "description" => "pomodoro, mozzarella, carciofini, olive nere, funghi champignon, uovo sodo e prosciutto crudo",
    "price" => 6.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Margherita Amatriciana",
    "slug" => "margherita-amatriciana",
    "image" => "https://www.pizzainncasa.com/wp-content/uploads/2019/01/pizza-all-Amatriciana-1.jpg",
    "description" => "pomodoro, mozzarella, pancetta e pecorino",
    "price" => 6.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Supplì con Cacio e Pepe Artigianal",
    "slug" => "supplì-con-cacio-e-pepe-artigianal",
    "image" => "https://moondo.info/wp-content/uploads/2018/05/suppl%C3%AC-cacio-e-pepe.jpg",
    "description" => "più leggero e croccante con farina di mais",
    "price" => 1.80,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Supplì Chic",
    "slug" => "supplì-chic",
    "image" => "https://www.italiachiamaitalia.it/wp-content/uploads/2016/08/28683-suppli.gif",
    "description" => "bianco con mozzarella e tartufo nero di norcia nuovo",
    "price" => 2.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  //prodotti ristorante id=2 (da id 14 a id 28)
  [
    "restaurant_id" => 2,
    "name" => "Sushi Bento 12 Pezzi",
    "slug" => "sushi-bento-12-pezzi",
    "image" => "http://upload.wikimedia.org/wikipedia/commons/6/65/Assortment_of_sushi,_May_2010.jpg",
    "description" => "2 nigiri salmone, 1 nigiri gambero reale, 1 nigiri pesce bianco, 4 uramaki california e 4 hosomaki salmone",
    "price" => 11.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Nigiri Sho 6 Pezzi",
    "slug" => "nigiri-sho-6-pezzi",
    "image" => "https://c.pxhere.com/photos/e9/c9/Fresh_healthy_Sushi_Tasty-1619084.jpg!d",
    "description" => "3 nigiri salmone, 1 nigiri gambero reale, 1 nigiri pesce bianco e 1 nigiri tonno",
    "price" => 8.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Sushi Sho 10 Pezzi",
    "slug" => "sushi-sho-10-pezzi",
    "image" => "https://www.chedonna.it/wp-content/uploads/2018/05/sushi-1-1280x720.jpg",
    "description" => "10 nigiri sake",
    "price" => 14.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Sushi Special 14 Pezzi",
    "slug" => "sushi-special-14-pezzi",
    "image" => "https://www.repstatic.it/content/nazionale/img/2019/09/30/144925162-24d817c9-925f-4613-ad48-3df84283632c.jpg",
    "description" => "2 nigiri salmone, 1 nigiri gambero reale, 2 nigiri pesce bianco, 1 nigiri tonno, 4 hosomaki salmone e 4 hosomaki avocado",
    "price" => 12.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Chanel Tris di Pesce",
    "slug" => "chanel-tris-di-pesce",
    "image" => "http://cakegardenproject.com/wp-content/uploads/2016/09/sushi_11.jpg",
    "description" => "riso sushi, salmone, tonno, spigola, avocado, cipolla fritta croccante, edamame, finocchio, mango, radicchio, tobiko, wakame e semi di sesamo",
    "price" => 14.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Pukas Salmone Grill",
    "slug" => "pukas-salmone-grill",
    "image" => "https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/styles/im_landscape_100/public/fdl_content_import_it/kaiten-sushi-come-funziona.jpg?itok=3nbC9x85",
    "description" => "riso sushi, salmone grigliato, avocado, cipolla fritta croccante, edamame, finocchio, mango, radicchio, tobiko, wakame e semi di sesamo",
    "price" => 13.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Emmery Tonno",
    "slug" => "emmery-tonno",
    "image" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCVuY8J7vWTlGKecfnGowCe9o6GZvO9T9n1w&usqp=CAU",
    "description" => "riso sushi, tonno, avocado, cipolla fritta croccante, edamame, finocchio, mango, radicchio, tobiko, wakame e semi di sesamo",
    "price" => 13.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Kauai Spigola",
    "slug" => "kauai-spigola",
    "image" => "https://amilanopuoi.com/wp-content/uploads/2017/01/A-Milano-puoi_Jin-1024x1024.jpg",
    "description" => "iso sushi, spigola, avocado, carote, edamame, finocchio, insalata di misticanza, mais, mango, pomodorini, radicchio e semi di sesamo",
    "price" => 13.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Involtini Primavera",
    "slug" => "involtini-primavera",
    "image" => "https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/styles/open_graph_image/public/fdl_content_import_it/involtini-primavera-vegani.jpg?itok=vprWLKF4",
    "description" => "verza bianca e carote freshly homemade, 3 pezzi",
    "price" => 2.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Ravioli di Carne al Vapore",
    "slug" => "ravioli-di-carne-al-vapore",
    "image" => "https://tempodicottura.it/wp-content/uploads/2018/05/MG_2675.jpg",
    "description" => "verza bianca e carne di maiale, 4 pezzi",
    "price" => 3.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Onion Rings",
    "slug" => "onion-rings",
    "image" => "https://i.pinimg.com/originals/85/ee/b7/85eeb71ee3d0df94c7656149a32fefbc.jpg",
    "description" => "croccanti anelli di cipolla fritti tipici della cucina americana, 8 pezzi",
    "price" => 3.50,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Ravioli di Verdure al Vapore",
    "slug" => "ravioli-di-verdure-al-vapore",
    "image" => "https://www.latavernadegliarna.it/wp-content/uploads/2018/07/ravioli-aperti-aperti-con-verdure-grigliate-10-07-2018_DSC6384.jpg",
    "description" => "farina di grano, acqua, verza, sale, olio d'oliva, carota cinese e spinaci, 4 pezzi",
    "price" => 3.50,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Ravioli di Verdure alla Griglia",
    "slug" => "ravioli-di-verdure-alla-griglia",
    "image" => "https://i.pinimg.com/736x/67/99/32/679932e2bf602f5b17ff26b1acf27f98.jpg",
    "description" => "farina di grano, acqua, verza, sale, olio d'oliva, carota cinese e spinaci, 4 pezzi",
    "price" => 4.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Pad Thai di Pollo",
    "slug" => "pad-thai-di-pollo",
    "image" => "https://paneburroezuccheroblog.files.wordpress.com/2020/10/pollo-melagrana3.jpg",
    "description" => "tagliatelle di riso thailandese, carote, verza bianca, zucchine, uova, pollo fritto croccante, salsa thailandese, salsa teriyaki condito con granella di noccioline tostate e lime",
    "price" => 8.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Pad Thai Frutti di Mare",
    "slug" => "pad-thai-frutti-di-mare",
    "image" => "https://staccaeviaggia.com/wp-content/uploads/2020/03/pad-thai-1024x768.jpg",
    "description" => "tagliatelle di riso tailandesi, carote, verza bianca, zucchine, uova, gamberi, polpa di granchio, calamari, salsa thailandese ,salsa teriyaki condita con granella di noccioline tostate, salsa teriyaki e lime",
    "price" => 9.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  //prodotti ristorante id=3 (da id 29 a id 34)
  [
    "restaurant_id" => 3,
    "name" => "Genovese di Tonno",
    "slug" => "genovese-di-tonno",
    "image" => "https://www.claravarriale.it/wp-content/uploads/2019/06/genovese.jpg",
    "description" => "tonno fresco scottato in padella, crema di cipolla, battuto di prezzemolo a scelta e cacio ricotta a scelta",
    "price" => 9.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 3,
    "name" => "Orecchiette ragù",
    "slug" => "orecchiette-ragù",
    "image" => "http://cucinaconmegraziellaeraffaele.it/wp-content/uploads/2020/03/inbound8333691981093346372.jpg",
    "description" => "ragù di manzo italiano e cacioricotta a scelta",
    "price" => 9.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 3,
    "name" => "Orecchiette Cime di Rapa",
    "slug" => "orecchiette-cime-di-rapa",
    "image" => "https://lh3.googleusercontent.com/proxy/Kmf7odXIcfXOApHN6IZhT-hVe0RSBfhBijH-SPfV17QJaTFendoqVthGm3gR1z4hQVn5jnSMxCHDuXmQXwYJEf0-zk3-_G8iWUm13ETJMO_91DeUPsnuswyqWbheW_gEWPSViakbjoAzOiZor9OYog",
    "description" => "cime di rapa, olio extravergine d'oliva e battuto di alici a scelta",
    "price" => 8.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 3,
    "name" => "Pomodori Scattarisciati",
    "slug" => "pomodori-scattarisciati",
    "image" => "https://www.sfiziosalentino.it/wp-content/uploads/2019/09/pomodori-scattarisciati-prodotti-tipici-salentini-online-1-1200x1043.jpg",
    "description" => "pomodoro fresco soffritto, peperone cornetto e basilico",
    "price" => 5.50,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 3,
    "name" => "Pasticciotti Crema Classica",
    "slug" => "pasticciotti-crema-classica",
    "image" => "https://www.ricettedalmondo.it/images/foto-ricette/p/31681-pasticciotto-scomposto-2.jpg",
    "description" => "pasta frolla e crema pasticcera",
    "price" => 2.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 3,
    "name" => "Pasticciotti Pistacchio",
    "slug" => "pasticciotti-pistacchio",
    "image" => "https://4.bp.blogspot.com/-M6xIV7UQQiw/WaJ9fCzahOI/AAAAAAABFRk/xfmR-dWc-d00YM4fGfEptQTqJO5_Ggz-gCLcBGAs/s1600/IMG_0656_WT.jpg",
    "description" => "pastra frolla con granella di pistacchio e crema ai pistacchi",
    "price" => 2.20,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  //prodotti ristorante id=4 (da id 35 a id 41)
  [
    "restaurant_id" => 4,
    "name" => "Pagnottella Pantera Rosa",
    "slug" => "pagnottella-pantera-rosa",
    "image" => "https://www.fabiobarbatopersonalchef.com/wp-content/uploads/2016/07/Pagnottelle-rustiche-2.jpg",
    "description" => "prosciutto cotto, pomodoro a fette, insalata e salsa rosa",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 4,
    "name" => "Pagnottella Friarielli Vivo",
    "slug" => "pagnottella-friarielli-vivo",
    "image" => "https://www.cucinasud.it/images/2020/01/23/babasasicce_large.jpg",
    "description" => "salsiccia, provola affumicata e friarielli",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 4,
    "name" => "Pagnottella al Volo",
    "slug" => "pagnottella-al-volo",
    "image" => "https://www.tutored.me/it/wp-content/uploads/sites/13/2016/10/pantelleria_homepage-e1476436647609.jpg",
    "description" => "tonno, pomodoro a fette, insalata e salsa rosa",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 4,
    "name" => "Pagnottella Pesto, Caprino e Pomodori Secchi",
    "slug" => "pagnottella-pesto-caprino-e-pomodori-secchi",
    "image" => "https://2.bp.blogspot.com/_lmT8xlMCBaM/TNO1dtyz8UI/AAAAAAAAAic/tJ84DqLcYyA/w1200-h630-p-k-no-nu/cestini+salsiccia+radicchio+caprino2-2.jpg",
    "description" => "mozzarella , pesto , caprino e pomodori secchi",
    "price" => 6.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 4,
    "name" => "Le Ripiene Pizza Romana",
    "slug" => "le-ripiene-pizza-romana",
    "image" => "https://www.scattidigusto.it/wp-content/uploads/2013/07/fazzoletto-parmigiana-melanzane-Gabriele-Bonci-32.jpg",
    "description" => "mortadella, salsa tartufata e mozzarella",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 4,
    "name" => "Parmense",
    "slug" => "parmense",
    "image" => "https://i.pinimg.com/originals/98/52/5e/98525e7f89ff82fc1fb3da293b7bc962.jpg",
    "description" => "rughetta, pomodorini, prosciutto crudo e mozzarella",
    "price" => 6.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 4,
    "name" => "Focaccia Vegetariana",
    "slug" => "focaccia-vegetariana",
    "image" => "https://www.ristorazioneitalianamagazine.it/CMS/wp-content/uploads/2018/02/04-Pizza-con-la-cicoria-1.jpg",
    "description" => "mozzarella, peperoni, melanzane e zucchine",
    "price" => 7.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  //prodotti ristorante id=5 (da id 42 a id 43)
  [
    "restaurant_id" => 5,
    "name" => "Fusilli di Mais",
    "slug" => "fusilli-di-mais",
    "image" => "https://www.lospicchiodaglio.it/img/ricette/pastaspeckradicchio.jpg",
    "description" => "Fusilli di Mais e Riso con Speck e Zafferanoe",
    "price" => 8.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 5,
    "name" => "Lasagna",
    "slug" => "lasagna",
    "image" => "https://www.smeg.com/binaries/content/gallery/smeg-italy/news/8-lasagne-bolo.jpg/8-lasagne-bolo.jpg/brx%3ApostcardDeskLarge",
    "description" => "Lasagna alla Bolognese, con spalla di manzo",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  //prodotti ristorante id=6 (da id 44 a id 45)
  [
    "restaurant_id" => 6,
    "name" => "Burrito con Chili",
    "slug" => "burrito-con-chili",
    "image" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2018/03/burrito-di-carne/jcr:content/header-par/image-single.img10.jpg/1521454018401.jpg",
    "description" => "chili con carne di nostra produzione, riso, insalata, salsa guacamole, salsa ranch, panna acida e jalapeno a fette",
    "price" => 7.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 6,
    "name" => "Burrito Picadillo",
    "slug" => "fajitas-picadillo",
    "image" => "https://i.pinimg.com/originals/9e/39/14/9e3914115af65f7c5d859124fc880d79.jpg",
    "description" => "carne di manzo con polpa di pomodoro, peperoni a striscioline e jalapeno, insalata, riso, panna acida e salsa ranch",
    "price" => 7.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  //prodotti ristorante id=7 (da id 46 a id 47)
  [
    "restaurant_id" => 7,
    "name" => "Chatpatta Allo",
    "slug" => "chatpatta-alloo",
    "image" => "https://i0.wp.com/www.curryandvanilla.com/wp-content/uploads/2018/11/chatpata-aloo-tuk-d.jpg?resize=600%2C629&ssl=1",
    "description" => "patate salate in salsa di menta e coriandolo",
    "price" => 5,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 7,
    "name" => "Tandoori Chicken Senza Glutine",
    "slug" => "Tandoori-chicken-senza-glutine",
    "image" => "https://spicecravings.com/wp-content/uploads/2020/12/Tandoori-Chicken-Wings-featured-1.jpg",
    "description" => "cosce di pollo marinate e cotte al tandoori",
    "price" => 7,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  //prodotti ristorante id=8 (da id 47 a id 54)
  [
    "restaurant_id" => 8,
    "name" => "Crêpes Suprema XV Fondente",
    "slug" => "crepes-suprema-xv-fondente",
    "image" => "https://static9.depositphotos.com/1026029/1115/i/950/depositphotos_11155466-stock-photo-sweet-pancake-with-chocolate-sauce.jpg",
    "description" => "tre semplici ingredienti si uniscono per dare vita a una ricetta unica che celebra la tradizione piemontese, le nocciole piemonti Igp e pregiato cacao si uniscono grazie all'olio extravergine d'oliva",
    "price" => 4.9,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 8,
    "name" => "Nocciolato Mignon Piemonte Fondente",
    "slug" => "nocciolato-mignon-piemonte-fondente",
    "image" => "https://i.pinimg.com/originals/71/16/32/7116322fdc267afe85b95bcf70b65364.jpg",
    "description" => "Uovo fondente rivestito internamente di Nocciole Piemonte IGP  (65g)",
    "price" => 10,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 8,
    "name" => "Portaovetti Ripieni",
    "slug" => "portaovetti-ripieni",
    "image" => "https://www.pourfemme.it/wp-content/uploads/sites/2/np-gallery/2015/03/ovetti-ripieni_41891.jpg",
    "description" => "Portaovetti con golosi ovetti ripieni assortiti. (60g)",
    "price" => 5,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 8,
    "name" => "Ovetti Confettati",
    "slug" => "ovetti-confettati",
    "image" => "https://cdn.acquadrodolciumi.it/files/articles/buratti-ovetti-confettati-500g-g45dy.jpg",
    "description" => "Fai la scorta di uova Confettate ricoperte da un croccante guscio di zucchero naturalmente colorato. (140g)",
    "price" => 19,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 8,
    "name" => "Coniglio di Pasqua",
    "slug" => "coniglio-di-pasqua",
    "image" => "https://image.freepik.com/free-photo/beautiful-decorated-easter-eggs-with-chocolate-bunny_169016-5165.jpg",
    "description" => "Un morbidissimo peluche, perfetto per grandi e piccini, con una sorpresa golosa! (110g)",
    "price" => 18,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 8,
    "name" => "Uovo Latta",
    "slug" => "uovo-latta",
    "image" => "https://www.caffeologia.it/1963-medium_default/uovo-venchi-gran-nocciolato-latte-piemonte-540g.jpg",
    "description" => "Assortimento di ovetti di Pasqua bianco salati e nocciolati in una graziosa scatolina regalo apribile in latta a forma di uovo. Nelle nostre uova la vera sorpresa è il cioccolato! LIMITED EGG-DITION! (55g)",
    "price" => 6,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 8,
    "name" => "Sleeve Piccola",
    "slug" => "sleeve-piccola",
    "image" => "https://2.bp.blogspot.com/-Ir1GMYDVPTE/XAmaUJnnNzI/AAAAAAAAgqk/ENwlvxN9dGc13HzsKnqDahKaRxEADUKpgCLcBGAs/s1600/cappelliera%2BVenchi.jpg",
    "description" => "La nostra classica Sleeve ripiena di ovetti di Pasqua. Cosa aspetti ad assaggiarli tutti? (220g)",
    "price" => 10,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 8,
    "name" => "Cucciolo Fido Al Latte",
    "slug" => "cucciolo-fido-al-latte",
    "image" => "https://acquisti.corriere.it/wp-content/uploads/2021/03/15-2.jpg",
    "description" => "Cuccioli di cioccolato al latte, perfetti per una pausa di piacere. (50g)",
    "price" => 11.9,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  //prodotti ristorante id=9 (da id 55 a id )
  [
    "restaurant_id" => 9,
    "name" => "Menù Panino Kebab",
    "slug" => "menu-panino-kebab",
    "image" => "https://i1.wp.com/images.liveuniversity.it/sites/2/2014/06/kebab.jpg",
    "description" => "panino doner kebab, patatine fritte e 1 bibita a scelta",
    "price" => 9.1,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 9,
    "name" => "Menù Panino Falafel",
    "slug" => "menu-panino-falafel",
    "image" => "http://www.cucinasemplicemente.it/wp-content/uploads/2016/03/falafel-600x399.jpg",
    "description" => "panino falafel, patatine fritte e 1 bibita a scelta",
    "price" => 8.45,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 9,
    "name" => "Menù Cotoletta",
    "slug" => "menu-cotoletta",
    "image" => "https://www.sfizioso.it/wp-content/uploads/2017/03/panino-cotoletta-2.jpg",
    "description" => "panino cotoletta, patatine fritte e 1 bibita a scelta",
    "price" => 9.1,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 9,
    "name" => "Menù Wurstel",
    "slug" => "menu-wurstel",
    "image" => "https://hips.hearstapps.com/elleit.h-cdn.co/assets/17/44/640x320/landscape-1509358473-gettyimages-645896215.jpg?resize=640:*",
    "description" => "panino wurstel, patatine fritte e 1 bibita a scelta",
    "price" => 9.1,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 9,
    "name" => "Piatto Doner Kebab",
    "slug" => "piatto-doner-kebab",
    "image" => "https://st2.depositphotos.com/1020618/11240/i/600/depositphotos_112405614-stock-photo-close-up-of-kebab-sandwich.jpg",
    "description" => "con riso, patate e insalata, carne di vitello e tacchino, salse di yogurt e piccante",
    "price" => 10.4,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 9,
    "name" => "Falafel",
    "slug" => "falafel",
    "image" => "https://static.wixstatic.com/media/4d1a0a_c79eb988da4b431b90ae7e27290b3623~mv2.png/v1/fill/w_2000,h_1332,al_c,q_90,usm_0.66_1.00_0.01/4d1a0a_c79eb988da4b431b90ae7e27290b3623~mv2.webp",
    "description" => "polpette di ceci e verdure macinate e spezie 2 pezzi",
    "price" => 2.6,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 9,
    "name" => "Baklava",
    "slug" => "baklava",
    "image" => "https://i.pinimg.com/originals/fe/8c/0a/fe8c0add95f22d774697e2f49497fce8.jpg",
    "description" => "pasta sfoglia, burro, pistacchio e sciroppo di zucchero 3 pezzi",
    "price" => 3.25,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 9,
    "name" => "Kadayif",
    "slug" => "kadayif",
    "image" => "https://thumbs.dreamstime.com/b/kataifi-kadayif-kunafa-baklava-pastry-nests-cookies-pistachios-tea-cooking-sweets-turkish-arabic-traditional-ramadan-146546055.jpg",
    "description" => "pasta grattugiata, pistacchio e sciroppo di zucchero 1 pezzo",
    "price" => 3.9,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],

];
